@baseUrl = http://localhost:5285/

@membershipId = 66fdfb6a-bcb9-49e2-86be-19816695051e
@bookId = 66fdfb6a-bcb9-49e2-86be-19816695051e

### Loan book

POST {{baseUrl}}/api/membership/{{membershipId}}/books/{{bookId}}/loan

### Return book

PUT {{baseUrl}}/api/membership/{{membershipId}}/books/{{bookId}}/return

### Prolong loaned book

PUT {{baseUrl}}/api/membership/{{membershipId}}/books/{{bookId}}/prolong

### Reserve book

POST {{baseUrl}}/api/membership/{{membershipId}}/books/{{bookId}}/reserve

### Cancel book reservation

PUT {{baseUrl}}/api/membership/{{membershipId}}/books/{{bookId}}/cancel-reservation